# DATASOURCE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/datarest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  server:
    port: 8080
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  #flyway
  flyway:
    enabled: false
    baselineOnMigrate: false
